### ISSUE TITLE
Can't Import fasttext

### ISSUE THREAD

**Issue by MohammadHeydari** [neuperc/fastText-Persian#1]
I Can't Import fasttext even  after installed the VS 2014.
Solution: 
https://stackoverflow.com/questions/45377306/fasttext-for-python-module-fasttext-has-no-attribute-load-model

```
from gensim.models.wrappers import FastText 
Load the binary

model=FastText.load_fasttext_format('wiki.simple.bin')
```

**Comment by HamedHemati** [comment]
The code doesn't use gensim to load fastText pretrained models. As explained in the Jupyter notebook, you first need to install fastText as explained in the link below:
https://github.com/facebookresearch/fastText/tree/master/python
*You can quickly install it by: pip install fasttext
I also made minor changes to the notebook and it works now with the new version of fastText.

**Comment by MohammadHeydari** [comment]
> I also made minor changes to the notebook and it works now with the new version of fastText.
Thanks for your comment dear hamed
