### ISSUE TITLE
I'm Getting the "MemoryError: std::bad_alloc" error

### ISSUE THREAD

**Issue by MohammadHeydari** [neuperc/fastText-Persian#2]
Hello Hamed. after I downloaded the fasttext pre-trained vector for Persian and tried to run the sample code, I'm Getting the "MemoryError: std::bad_alloc" error, is there any way to handle it?
MemoryError                               Traceback (most recent call last)
<ipython-input-5-e08b8357dd7f> in <module>
      1 # load the model
      2 fastText_model_path = 'cc.fa.300.bin'
----> 3 model = fasttext.load_model(fastText_model_path)

~/anaconda3/lib/python3.7/site-packages/fasttext/FastText.py in load_model(path)
    348     """Load a model given a filepath and return a model object."""
    349     eprint("Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.")
--> 350     return _FastText(model_path=path)
    351 
    352 

~/anaconda3/lib/python3.7/site-packages/fasttext/FastText.py in __init__(self, model_path, args)
     41         self.f = fasttext.fasttext()
     42         if model_path is not None:
---> 43             self.f.loadModel(model_path)
     44         self._words = None
     45         self._labels = None

MemoryError: std::bad_alloc

**Comment by HamedHemati** [comment]
Hi Mohammad. fastText checkpoints are large and therefore you need to make sure that you have enough free RAM on your computer (sometimes up to roughly 5-6 GBs depending on the pre-trained vector) before loading them. You can run the notebook without any issues on Google Colab but of course you first need to install the `fasttext` package using pip and download the pre-trained vector which can take some minutes! 
*alternative solution: download it to your GDrive and directly load it from your GDrive for future use to save some time :)

**Comment by MohammadHeydari** [comment]
> Hi there bro. Thanks for the comment Hemd. Colab usually is a good option and increasing memory is crucial for a data scientist. anyway, I downloaded the pre-trained model.
